# Generated by Django 2.0 on 2020-02-09 11:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktracker',
            name='update_type',
            field=models.DateField(verbose_name=datetime.timedelta(days=7)),
        ),
    ]
