# Generated by Django 2.0 on 2020-02-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0002_auto_20200209_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktracker',
            name='task_type',
            field=models.IntegerField(),
        ),
    ]
